apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: onkar1502/wanderlust-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: FRONTEND_URL
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_URI
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: ACCESS_COOKIE_MAXAGE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ACCESS_COOKIE_MAXAGE
            - name: ACCESS_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ACCESS_TOKEN_EXPIRES_IN
            - name: REFRESH_COOKIE_MAXAGE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REFRESH_COOKIE_MAXAGE
            - name: REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REFRESH_TOKEN_EXPIRES_IN
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
