apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: wanderlust
data:
  # MongoDB Atlas Cloud Database Connection
  MONGODB_URI: "mongodb+srv://onkarsonawane2003_db_user:ubCq4Y08HHvrTZcY@cluster0.be6a8ea.mongodb.net/wanderlust?retryWrites=true&w=majority&appName=Cluster0"
  REDIS_URL: "redis://redis-service.wanderlust.svc.cluster.local:6379"
  PORT: "8080"
  FRONTEND_URL: "http://ad6a7b98aab8740b28a2ef4fbec287c2-1283267638.us-east-1.elb.amazonaws.com"
  ACCESS_COOKIE_MAXAGE: "120000"
  ACCESS_TOKEN_EXPIRES_IN: "120s"
  REFRESH_COOKIE_MAXAGE: "120000"
  REFRESH_TOKEN_EXPIRES_IN: "120s"
  NODE_ENV: "production"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: wanderlust
data:
  # Routed via AWS ELB Ingress Controller
  VITE_API_PATH: "http://ad6a7b98aab8740b28a2ef4fbec287c2-1283267638.us-east-1.elb.amazonaws.com/api"
